/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.felipero.binaryGap;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BinaryGapTest {
    @Test 
    void longestGapValidNumber() {
        BinaryGap binaryGap = new BinaryGap();
        assertEquals(binaryGap.longest(328), 2);
    }

    @Test
    void gapOfOne() {
        BinaryGap binaryGap = new BinaryGap();
        assertEquals(binaryGap.longest(20), 1);
    }

    @Test 
    void noGapAtAll() {
        BinaryGap binaryGap = new BinaryGap();
        assertEquals(binaryGap.longest(32), 0);
    }

    @Test 
    void longN() {
        BinaryGap binaryGap = new BinaryGap();
        assertEquals(binaryGap.longest(805306373), 25);
    }

    @Test
    void twoOnesInSequence() {
        BinaryGap binaryGap = new BinaryGap();
        assertEquals(binaryGap.longest(51712), 2);
    }
}
