/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.felipero.binaryGap;

public class BinaryGap {
    public Integer longest(int n) {
				String binaryRep = Integer.toBinaryString(n);
				
				int longestGap = 0;
				int currentGap = 0;
			
				for(int i=0; i < binaryRep.length(); ++i) {
				  char c = binaryRep.charAt(i);
				  if(c == '1') {
				    longestGap = currentGap > longestGap ? currentGap : longestGap;
				    currentGap = 0;
				  } else {
				    currentGap++;
				  }
				}
        return longestGap;
    }

    public static void main(String[] args) {
        System.out.println(new BinaryGap().longest(5));
    }
}
