/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package felipero.trees;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LevelOrderTraversalTest {
    @Test
    void testLevelOrder() {
        assertEquals("1 2 5 3 6 4", LevelOrderTraversal.execute("6 \n 1 2 5 3 6 4"));
    }

    @Test
    void testLevelOrder_with_50_nodes_tree() {
        String input = "50 \n 47 2 40 20 38 30 14 28 10 16 19 44 39 27 7 9 31 12 43 21 5 41 34 49 13 33 3 4 25 22 29 15 32 35 6 24 23 26 1 11 42 36 37 17 18 8 45 48 50 46";
        String expectedOutput = "47 2 49 1 40 48 50 20 44 14 38 43 45 10 16 30 39 41 46 7 12 15 19 28 31 42 5 9 11 13 17 27 29 34 3 6 8 18 21 33 35 4 25 32 36 22 26 37 24 23";
        assertEquals(expectedOutput, LevelOrderTraversal.execute(input));
    }

    @Test
    void testLevelOrder_with_15_nodes_tree() {
        String input = "15 \n 1 14 3 7 4 5 15 6 13 10 11 2 12 8 9";
        String expectedOutput = "1 14 3 15 2 7 4 13 5 10 6 8 11 9 12";
        assertEquals(expectedOutput, LevelOrderTraversal.execute(input));
    }
}